---
title: Thesis Plan / Rose McKeon / Sep 2019
#author: Rose McKeon
#date: "September 22nd 2019"
bibliography: assets/ploidy.bib
bibliographystyle: assets/crumpetBES.bst
output: 
  #word_document:
  pdf_document:
    template: assets/crumpet-proposal.tex
    citation_package: natbib
    keep_tex: no
    fig_caption: yes
    fig_width: 2.5
    fig_height: 2.5
    number_sections: false
    latex_engine: xelatex
---

<!--- BD: Just separating sentences on lines to make it easier to comment; this shouldn't affect the PDF after knitting --->
According to @Ramsey2014, polyploidisation is thought to be fundamental in the diversification of plant species due to polyploidy being a ubiquitous feature in the lineages of most plant taxa. <!--- BD: Can you expand on this as to why the ubiquity of polyploidy in plant lineages implies that it is fundamental to diversification? I'm not quite sure I follow the logic of how polyploidy necessarily must take a fundamental (presumably causal) role in plant diversification just because most lineages are polyploid (i.e., there are surely other plant traits that are ubiquitous, but not necessarily fundamental to diversity). Is the rationale something to do with a correlation between speciation events and polyploidy in phylogenies? --->
While polyploids have been studied for over a century, the factors that drive the success of their establishment in the face of reproductive disadvantages and high extinction rates are still unclear. 
Polyploidisation has been found to coincide with around 25% of plant speciation events [@Wood2009], however, a study by @Arrigo2012 on the extinction rates of polyploids has suggested that many of these new lines are evolutionary dead ends. <!--- BD: Ah, okay, here's more what I was looking for in terms of raitonale. So the idea is that polyploidy causes speciation, as evidence by speciation events in the phyolgeny appearing to coincide with increases in ploidy in new species? But @Arrigo2012 suggests that the newly formed polyploid species go extinct at a higher rate than non-polyploids? --->
They conclude that polyploids tend to become extinct at the establishment phase due to reproductive disadvantages such as lack of mates, diploid pollen swamping, and triploid sterility. <!--- BD: Nice, this feels like the start of a good set up for an interesting theoretical question. I'm now wanting to know whether or not these proposed mechanisms conferring a reproductive disadvantage are realistic. --->
Therefore, understanding demographics at the establishment phase is critical to predicting polyploidisation of plant species. <!--- BD: Agreed, but this would also be a good place for some more theory and guided thought -- help me and the reader think more clearly about  these different mechanisms, and when (or whether) each might be important. I could imagine, potentially, an entire dissertation paragraph on each of these in the Introduction. ---> 
Benefits associated with polyploidy may offset these costs: Polyploids are frequently linked with distinct traits such as "gigas effects", which include increases in plant organs, reversal of selfing inhibition, enhanced capabilities for buffering of deleterious mutation (due to increased heterozygosity), and hybrid vigour (heterosis) [@Woodhouse2009; @Ramsey2014]. <!--- BD: Good, though same as above -- I could imagine a paragrpah or more of each of these in a dissertation Introduction .--->
These traits are thought to overcome the reproductive disadvantages of polyploidy and instead make this mutation key to the invasive and adaptive potential of plants, ultimately shaping broader patterns of plant diversification.

<!-- BD: You've identified several really relevant costs and benefits to polyploidy. I think it would be good to think about them all individually, and which ones you think are likely to be most important or most interesting. A good theory dissertation or manuscript doesn't need to look at everything. Actually, I think that a lot of really good theory work focuses on one mechanism of interest to understand it more clearly (much like an experiment might try to test how one factor affects something in a system). One useful approach for you might be to try pin down what you think is the most interesting process affecting polyploidy (after doing some background reading on each), or the one that sounds most suspicious (i.e., if you read something and think -- "that doesn't sound completely plausible -- what if x, y, or z?"). If you were to show, for example, that pollen swamping is unlikely under most conditions (all else being equal), that would be enough for a good paper. You could also think about interesting ways to link the costs and benefits -- maybe, e.g., pollen swamping is important because it is predicted to cause selection for reversal of selfing inhibition (again, all else being equal). --->

In natural populations, polyploids maintain distinct spatial distributions relative to progenitors and other diploids, suggesting the importance of polyploidy as a mechanism of ecological divergence [@Ramsey2014]. <!--- BD: Interesting -- why is this? Is this just because polyploids are effectively arising in a particular location and expanding out from there? I wonder if there is a competitive argument for polyploid establishment? E.g., if diploids experience more total competition relative to polyploids, and polyploids are competitively dominant under some particular environmental conditions? --->
Recent niche modelling, however, has not supported this theory and proposes that glacial retreat and environmental disturbance (conditions which correlate with increased polyploid frequency) may be more influential [@Godsoe2013]. <!-- BD: Also cool! ---> 
This research will aim to advance theoretical understanding of the evolution of polyploids in plant systems by examining the interplay between whole-genome duplication events, environmental factors and traits which embue individuals with costs/benefits. 
**The exact question for my project is not compeletely nailed down. I'm attempting to find the key gap in our undestanding of the theory in order to choose an appropriate question to test.**

<!--- BD: I'm starting to think that it might help to narrow down a bit on one or two mechanisms that you find most interesting or potentially fruitful in terms of theoreticla questions. You've got a really good grasp of what ideas have been proposed for the costs and benefits of polyploidy. There are a lot of interesting places you can go to from here. The most difficult would be to introduce an entirely new idea of how polyploidy might arise and spread (new costs or benefits), assuming one(s) exists. The second most difficult would probably be to show that one or more of these costs and benefits hypothesised do not actually make sense -- i.e., that the prediction (hypothesis) does not follow logically from the starting assumptions. A bit more manageable for a dissertation would be to try to flesh out one or two of these mechanisms and ask some questions about the conditions that it specifically is predicted to contribute substantially to diversification of polyploids -- e.g., are there reasons to think that pollen swamping will lead to dead ends under some conditions, but diversification (or at least not dead ends) under others? --->

## Methodology: 

This study aims to advance theoretical understanding of the evolution of polyploids by means of an individual based model (IBM), a method which has not yet been fully applied to this problem. <!--- BD: Good, but see above -- I think you need to narrow in on a clearer problem --->
By simplifying a complex biological system into a model one, then manipulating its variables and underlying biological processes, biological patterns (such as species distribution) can be revealed. 
Analysis of these patterns can make sense of relationships which are hard to pinpoint in natural environments.  

The model will be developed based on the [DisturPloidy](https://github.com/rosemckeon/ploidy/) R package, which I created over the summer. <!--- BD: Maybe rephrase, just to make clear that the summer work was not part of your dissertation, per se. Rather, you'll use R and an assortment of R packages to write and IBM, including a package that you wrote over the summer, which you will expand by writing new code to specifically address question X. --->
Additions/improvements will be made according to the specifics of the research question.
Simulated plants will be initialised on a spatially explicit landscape. 
Their genomes will be modelled so that polyploidy can occur mechanistically. 
Fitness costs and benefits of polyploidy will also be represented genomically so these traits can arise naturally, vary between individuals and be subject to selection. 
Repeated simulations will be run with atleast 30 replicates per simulation. 
Method of analysis will depend on the exact requirements of the question, but bootstrapped confidence intervals of the replicates will no doubt be created. <!--- BD: All this sounds good, but will likely be tailored more specifically to the question you set up --->

### Ethics: 
There are no ethics concerns for this project.

### Timetable of Planned work: 
I have set up a private GitHub repository for the writing of my thesis. 
Project management will be carried out here; milestones, project cards, and issues already in progress have been added accordingly. 
I have invited you as a collaborator so you can access all aspects [here](https://github.com/rosemckeon/honours-project).

### Summary of Resources Required:
I will need computing power to run replicate simulations.

<!--- BD: This all looks great! I'm excited to see where this ambitious project takes you. Let's keep meeting regularly, and let me know if you start to feel like you're getting stuck, especially early on during the question forming stage --->



