
# Conclusion {#conclusion}

Increasing the frequency of unreduced gametes in the system modelled did give evolving neopolyploids enough of an advantage to overcome the combined cost of triploid sterility and pollen-swamping. In order for them to fully overcome the strength of negative selection working against them, the rate of nonreduction needed to be 83-fold greater than what we see in nature. At this high rate of nonreduction, between 0.464 and 0.5 there was a 7.0% chance that polyploidy would evolve to stable fixation, a 21.1% chance of unstable fixation, and a 71.9% chance of total extinction, where both diploid progenitors and evolving polyploids were eradicated. Evolving neopolyploids could also become fixated at tiny population sizes where one or two individuals would persist. Unstable fixation only occurred when the rate was 27-fold greater than what we see in nature. At these nonreduction rates between 0.152 and 0.464, there was 31.7% chance of polyploidy becoming fixated and a 68.3% chance of total extinction. Established populations suffered no less extinction than pioneering ones, though pioneering populations did reach their fate more quickly when they were doomed to failure.

The relative abundances of diploids, sterile polyploids and viable polyploids followed distinct trends depending on the rate. Between nonreduction rates of 0 and 0.152, stable coexistence between all ploidy types was achieved 100% of the time. Diploids predominated, followed by sterile polyploids, with viable polyploids persisting at the lowest relative abundances. As the rate was increased through that range, the relative abundances of sterile and viable polyploids increased until both diploid and sterile polyploid abundances were close to 0.5, with diploids just over and sterile polyploids just under. Viable polyploids, at this point, were on the cusp of reaching a relative abundance that matched half the rate of nonreduction (0.076). Once that cusp was reached, sterile polyploid and diploid relative abundances collided around 0.5 and 100% of the populations were sent into a period of instability. During this turbulent phase, diploid abundance declined 100% of the time, with greater speed as the rate of nonreduction was increased. High relative abundances of sterile polyploids persisted around and over 0.5 long after diploid decline. Therefore, there was substantial sterile polyploid generation from the viable polyploid population due to interploidy fertilisation attempts between incompatible gametes. However, in all instances, viable polyploid abundance tended to be just above that of the sterile polyploids. Whether or not they managed to escape the production of sterile polyploids in order to become fixated was entirely down to chance. 

When rare gametes meet, evolving polyploids can readily establish and persist at low relative abundances alongside their diploid progenitors, without any need for adaptation. However, these results also indicate that if polyploids did evolve such beneficial traits in order that they could become more abundant, this scenario should most often lead to evolutionary 'dead-ends'. Viable polyploids attempting to reach establishment were almost always wiped out by chance because of the constant production of sterile offspring. In order for that not to be the case, the strength of triploid sterility in the system would need to be far less. If this was true, the struggle between viable and sterile polyploids on the road to fixation should be far less in the hands of chance. These results do not show that explicitly, but further work could be done to model variation in the strength of triploid sterility. The idea that this might improve the chances of polyploid fixation could then be tested in a system that reflects some of the ways that triploid sterility has been shown to vary in nature. 

