# Discussion {#discussion}

We have shown here how the extreme cost of pollen-swamping selects against the evolution of polyploidy. Polyploidy did not rise to fixation in a single simulation because of the dramatic effect these mating rules had on their ability to produce viable seeds. We have also shown how increasing the rate of whole-genome duplication caused reproductive interference across the entire landscape, swamping diploids and polyploids alike with incompatible pollen. The resulting reduction in fecundity doomed both diploids and polyploids to extinction. In effect, because of the model assumptions, increasing the rate of whole-genome duplication increased the diversity of mating types in the system. When no pollen specificity mechanisms existed to sort the mating pool so that these types could find each other effectively, the whole population was doomed to failure once enough different types were in the system. Therefore, it follows that this mate-choice limiting mutation must have a part to play in the evolution of beneficial traits that assist in compatibility assortment, such as; flower timing, pollinator specificity, and selfing. Could these mechanisms of mating assortment allow the population to escape extinction? 

>Are there reasons to think that pollen swamping will lead to dead ends under some conditions, but diversification (or at least not dead ends) under others?

Here we explore how mechanisms for compatibility assorting traits would work with the current model. We consider how these biological observations could be boiled down into a computational form, and we follow that, in each case, by discussing how these new conditions may be expected to change the pattern of results. 

## Delayed flowering {#discussion-escape-delayed-flowering}

Delayed flowering is often observed in autopolyploids due to their increased cell size and longer development times [@ref]. But rather than a cost that causes mate-limitation--as discussed in @ref--this could be thought of more as a strategy to escape the reproductive interference caused by diploid pollen swamping.
If the model presented here were expanded so that the parental pool--which is sampled randomly to create seeds--was further subdivided depending on ploidy level, then fertilisation attempts would only be carried out between compatible individuals. This subdivision would rudimentarily simulate the segregation we see in mating pools caused by phenological differences like delayed flowering. Furthermore, the interference we see caused by the rate of whole-genome duplication should vanish under these conditions. 

However, not all polyploids exhibit delayed flowering; for instance, many allopolyploid hybrids have intermediate phenotypes rather than enlarged ones [@ref]. To create some more natural variation, we could give individuals an inheritable trait value that denotes flowering time instead; a random uniform number between one and six perhaps for the months of spring and summer, with the lower values set to be more common by some probability. We could assume an equal flowering time of a single month, and subset the population to create parental mating pools by rounding these numbers to no decimal places. The trait values would be subject to mutation by a set rate during sexual reproduction, and polyploids could be gifted a higher chance of mutation to a value closer to six. This probability could depend on the number of sets of chromosomes that specific individual has, so for instance: an octoploid would have a higher chance of flowering in August than a tetraploid, but many polyploids would continue to flower at the same time as their parents. Under these conditions, we might see delayed flowering evolve in polyploid lineages, naturally assorting the mating pools and overcoming the pollen-swamping interference so that we see diversification rather than dead ends.

>Relate this to study system

## Pollinator specificity {#discussion-escape-pollinators}

Many flowering plants adjust their flower morphology, colour and nectar in order to attract very specific pollinators [@ref]. This acts to target pollen to specific compatible flower types in a complex and fascinating manner that relies on symbiosis with entirely separate species. This too could be a mechanism by which polyploids can escape pollen-swamping and increase their chances to reproduce in the face of extreme mate-limitation. Rather than add in explicit pollinators, this could be modelled in a similar way to the delayed flowering time. A random trait value for pollinator preference would be used to subset the population into mating pools. Therefore, the addition of a single sorting trait value would, in fact, test both the delayed flowering and pollinator specificity strategies, because they boil down to the same core process.

>Relate this to study system: see @Wise2011 for pollinator behaviour info

## Selfing {#discussion-escape-selfing}

Self-incompatibility is commonly found in angiosperms [@ref] and limits sexual reproduction via selfing. Various mechanisms control this by limiting the amount of self-pollination that can occur either by morphology, genetics or flower timing [@example?]. It has been hypothesised that reversal of self-incompatibility may be a route by which polyploidy evolves as it would remove constraints imposed by mate-limitation [@Stebbins1950]. In addition, multiple gene copies are thought to buffer against the deleterious effects of inbreeding depression [@ref]. While a general pattern of association between polyploidy and selfing has not been found across a wide range of taxa [@Mable2004], there has been some evidence for increased selfing in angiosperm tetraploids [@Cook2000; @Husband1997]. 

To investigate this mechanism further, we would need to restrict self-fertilisation in the model (under current assumptions, all individuals can self-fertilise). This could be done very simplistically by removing attempts where parental identifiers match. However, this approach would reduce the seed output as those attempts are removed and add a negative selection pressure to the system [think more about this, is that what we want?]. 

Perhaps a better method would be to elaborate the flower timing trait described above in order to allow the evolution of monoecy; separate male and female flowers which are freed to bloom at different times. However, this mechanism may not be such a good fit for the mating system actually observed in *E. guttata*. It would be relatively simple to add a second flower timing trait value so that the first defines the maternal mating pool, and the second the paternal. The model would need to begin with selfing disabled, i.e.:- the maternal and paternal flower timing trait values of any individual would need to differ by at least one whole number. This could be enforced by choosing maternal numbers at random and then resampling a paternal value until one that does not match is found. It would be important to make sure there was some overlap by using random numbers so that some mating was definitely able to occur; if all maternal flowers bloomed in month 1, and all paternal in month 6, then the population would not survive longer than one generation. Allowing these random values to mutate as before would enable us to see if selfing naturally evolves, and if so, whether it occurs more in polyploid or diploid lineages.

>I think the above might need scrapping.

While hermaphroditic flowers are the most commonly found in *E. guttata* [@Wise2011], male sterility genes have also been described [@Willis1999]. The variation found was considered ample enough to lead to the evolution of gynodioecy (females plus hermaphrodites), an intermediate step in the evolution of dioecy (separate male and female individuals) [@Charlesworth2006]. Investigation of potential constraints in the evolution of gynodioecy [@Wise2011] demonstrated that females had a reproductive advantage due to increased flower number, as well as ovule number per flower. In addition, the potential for this advantage to be even greater in the face of hermaphroditic inbreeding depression was raised; the theory being that females will necessarily outcross. However, the strength of these advantages appears only to keep the genes for male sterility at low frequencies wild *E. guttata* populations, as no fully gynodioecious population has been described.

>I've gone off on a tangent... what is the selfing mechanism in *E. guttata*? Check over the more recent papers Matty gave me about estimating outcrossing and selfing rates... pretty sure there isn't a decent method for this yet as that was part of the project, because the stats so far are better suited to obligate outcrossers. Do we even know how much selfing wild *E. guttata* already do?

They were mostly outcrossing with fluctuating partial selfing in two populations from Oregon [@Willis1993].

>Are these methods outdated or still valid?

>Also... what about geitonogamy? See @DeJong1993 and @Karron2004... adaptations that prevent selfing within a flower or by flower timing don't stop the transfer of pollen between individual flowers on the same plant, or a genetically identical one. It's common and increases with plants size. Selfing is getting complicated. Individual flowers aren't represented in the model. But if polyploids are bigger with more flowers, then it follows that more selfing would occur due to this mechanism as shown in the floral size comparisons of @Karron2004. Maaaaaybe this is why @Mable2004 did not find an association between polyploids and selfing across wider taxa when there is evidence it occurs in angiosperms--check which specific taxa that study attempted to generalise those findings to and make sure they were not mostly angiosperm.

Where diploid *M. annua* were seen to displace hexaploid relatives in multiple locations via pollen-swamping, selfing only minorly allowed the hexaploids to mitigate these effects. Escaping pollen-swamping via selfing was density-dependent and slight [@Buggs2006].

## Model limitations

The mechanism of genome-duplication modelled did not differentiate between diploid and polyploid progenitors; for every viable seed created there was a chance that its genome would double regardless of its ploidy level (which was the same as its parents). This, therefore, could be improved to better reflect the fact that polyploids have not been found to speciate by further genome-doubling at the same rate as diploids [@Mayrose2011; @Mayrose2014]. If the duplication rate were lowered in this manner for polyploids, it would alleviate some mate-limitation by reducing the diversity of ploidy level that arises in the system (i.e.:- octoploids, hexadecaploids, and so on). Under the current assumptions, individuals cannot mate successfully with those of differing ploidy level. Therefore, due to tetraploids producing more tetraploids, there would be an increased probability that their gametes might meet and become viable seeds; especially in simulations with particularly high duplication rates.

The modelling method used to increase cohort size (when transition probabilities were greater than 1) lacked some natural variation due to the sampling process used. The transition matrix used to parameterise the simulations presented here increased the cohort size of seedlings at every generation based on the previous generations seedling number. Some stochasticity around seedling number in every generation was maintained, however, by the transitions that controlled fecundity and germination; these decreased cohort size and so used a better sampling method to maintain variation in the actual number sampled based on the given probability. The impact this programming decision made on the overall predictions of the model is likely negligible.

>Should I even bother mentioning this? I am not sure I have managed to describe it a way that makes sense anyway.

Genetically, all neopolyploids that avoid extinction enter a period of diploidisation, by which duplicated genes are lost discriminantly via various mechanisms over many generations until a state of diploidy has returned [@Comai2005]. The model presented here included no rate or mechanism for this process. 

>Not really sure that matters? Probably not relevant. It is cool, in any case.
