#' @name survive
#' @title survive
#' @description Reduces population data based on probability of survival, or alternatively also returns the dead.
#' @author Rose McKeon
#' @param pop a population dataframe as generated by populate_landscape(), ie: nested by plant.
#' @param prob a number between 0 and 1 representing probability of survival (default = 1, all are very likely to survive).
#' @param dead logical value that determines if the dead are returned (default = FALSE).
#' @return dataframe of survivors, or a list containing survivors as well as the dead.
#' @export
survive <- function(pop, prob = 1, dead = F){
  # make sure we have the right kind of parameters
  stopifnot(
    is.data.frame(pop),
    nrow(pop) > 0,
    is.numeric(prob),
    between(prob, 0, 1),
    is.logical(dead)
  )
  # decide which plants die
  deaths <- rbinom(nrow(pop), 1, prob) == 0
  if(!length(which(deaths)) == 0){
    # only attempt removals if there are deaths
    if(dead == T){
      # return deaths if requested
      message("  Returning survivors and deaths as list.")
      return(
        list(
          survivors = pop[-which(deaths), ],
          deaths = pop[which(deaths), ]
        )
      )
    } else {
      # or just the survivors
      #message("  Returning survivors only.")
      return(pop[-which(deaths), ])
    }
  } else {
    # return whole pop as survivors when no deaths 
    #message("  Returning survivors only.")
    return(pop)
  }
}
